version: 2

project_name: sloth-runner

# Enable parallel builds for faster releases
gomod:
  gobinary: go

# Optimize build performance
before:
  hooks:
    - go mod download
    - go generate ./...
release:
  github:
    owner: chalkan3-sloth
    name: sloth-runner
  name_template: "🚀 sloth-runner v{{ .Version }}"
  mode: replace
  draft: false
  prerelease: auto
  footer: |
    ## 🦥 Sloth Runner Enterprise Edition

    ### 📦 Downloads
    
    Choose the appropriate binary for your platform:
    - **Linux AMD64**: `sloth-runner_v{{ .Version }}_linux_amd64.tar.gz` (with SQLite support)
    - **Linux ARM64**: `sloth-runner_v{{ .Version }}_linux_arm64.tar.gz` (with SQLite support)
    - **macOS AMD64**: `sloth-runner_v{{ .Version }}_darwin_amd64.tar.gz` (SQLite disabled)
    - **macOS ARM64**: `sloth-runner_v{{ .Version }}_darwin_arm64.tar.gz` (SQLite disabled)
    
    ### 🚀 Quick Install
    ```bash
    # Linux/macOS
    curl -L https://github.com/chalkan3-sloth/sloth-runner/releases/latest/download/sloth-runner_v{{ .Version }}_$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m | sed 's/x86_64/amd64/').tar.gz | tar xz
    chmod +x sloth-runner
    sudo mv sloth-runner /usr/local/bin/
    ```
    
    ### 📚 Documentation
    - [📖 Getting Started](https://chalkan3.github.io/sloth-runner/en/quick-start/)
    - [🌐 Multilingual Docs](https://chalkan3.github.io/sloth-runner/)
    - [💾 State Management](https://chalkan3.github.io/sloth-runner/en/modules/state/)
    - [📊 Telemetry & Monitoring](https://chalkan3.github.io/sloth-runner/en/telemetry/)

    ### 🆕 New Features
    - **Prometheus Telemetry**: Built-in metrics collection and export
    - **Terminal Grafana**: Rich terminal-based metrics dashboard
    - **Automatic Metrics**: Zero-configuration metrics collection

    **Full Changelog**: https://github.com/chalkan3-sloth/sloth-runner/compare/{{ .PreviousTag }}...{{ .Tag }}

builds:
  - id: linux-amd64
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - GOCACHE=/tmp/go-build-cache
    ldflags:
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -s -w
    flags:
      - -trimpath
      - -buildmode=pie
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/sloth-runner
    binary: sloth-runner

  - id: linux-arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - GOCACHE=/tmp/go-build-cache
    ldflags:
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -s -w
    flags:
      - -trimpath
      - -buildmode=pie
    goos:
      - linux
    goarch:
      - arm64
    main: ./cmd/sloth-runner
    binary: sloth-runner

  - id: darwin-amd64
    env:
      - CGO_ENABLED=0
      - GOCACHE=/tmp/go-build-cache
    ldflags:
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -s -w
    flags:
      - -trimpath
    goos:
      - darwin
    goarch:
      - amd64
    main: ./cmd/sloth-runner
    binary: sloth-runner

  - id: darwin-arm64
    env:
      - CGO_ENABLED=0
      - GOCACHE=/tmp/go-build-cache
    ldflags:
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -s -w
    flags:
      - -trimpath
    goos:
      - darwin
    goarch:
      - arm64
    main: ./cmd/sloth-runner
    binary: sloth-runner

archives:
  - name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999