name: build-and-test

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'site/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'site/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential sqlite3 libsqlite3-dev
        timeout-minutes: 2

      - name: Install Go dependencies
        run: |
          go mod download
          go mod verify
        env:
          GOPROXY: "direct"
          CGO_ENABLED: 1
        timeout-minutes: 3

      - name: Run tests with coverage
        run: |
          go test -v ./cmd/sloth-runner/... -coverprofile=coverage.out -timeout=2m
        env:
          CGO_ENABLED: 1
        timeout-minutes: 3

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage.out
