name: Minimal Test

on:
  workflow_dispatch:

jobs:
  minimal:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - run: pwd
      - run: ls -la
      - run: whoami
      - run: echo "SUCCESS"