name: Multi-Platform Build Test

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'site/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'site/**'

jobs:
  test-builds:
    name: Test Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential sqlite3 libsqlite3-dev

      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install sqlite3

      - name: Install Go dependencies
        run: go mod download
        timeout-minutes: 3

      - name: Build binary (Linux with SQLite)
        if: runner.os == 'Linux'
        run: |
          CGO_ENABLED=1 go build -v -o sloth-runner-test ./cmd/sloth-runner
        timeout-minutes: 5

      - name: Build binary (macOS without SQLite)
        if: runner.os == 'macOS'
        run: |
          CGO_ENABLED=0 go build -v -o sloth-runner-test ./cmd/sloth-runner
        timeout-minutes: 5

      - name: Test binary execution
        run: ./sloth-runner-test version || echo "Binary built successfully"
        timeout-minutes: 1

      - name: Upload test binary
        uses: actions/upload-artifact@v4
        with:
          name: sloth-runner-${{ matrix.os }}
          path: sloth-runner-test*
          retention-days: 1